[package]
name = "volt"
version = "0.1.0"
authors = ["Interfiber"]
edition = "2018"

[dependencies]
<<<<<<< HEAD
kas = "0.7.0"
kas-theme = "0.7.0"
kas-wgpu = "0.7.0"
native-dialog = "0.5.5"
curl = "0.4.35"
=======
# UI toolkits
kas = "0.7.0"
kas-theme = "0.7.0"
kas-wgpu = "0.7.0"
kas-text = "0.2.1"
# API requests(used to use curl)
isahc = "1.3.0"
# Json parsing fro CurseForge
serde_json = "1.0.64"
>>>>>>> :sparkles: Get basic API request working
